### ISSUE TITLE
Designer NPE

### ISSUE THREAD

**Issue by rcketscientist** [FutureMind/recycler-fast-scroll#32]
Following the basic example I end up with this error in the designer:

```
java.lang.NullPointerException
    at com.futuremind.recyclerviewfastscroll.FastScroller.initHandleMovement(FastScroller.java:186)
    at com.futuremind.recyclerviewfastscroll.FastScroller.onLayout_Original(FastScroller.java:162)
    at com.futuremind.recyclerviewfastscroll.FastScroller.onLayout(FastScroller.java)
    at android.view.View.layout(View.java:17520)
    at android.view.ViewGroup.layout(ViewGroup.java:5612)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
    at android.view.View.layout(View.java:17520)
    at android.view.ViewGroup.layout(ViewGroup.java:5612)
    at android.support.v4.widget.DrawerLayout.onLayout_Original(DrawerLayout.java:1197)
    at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java)
    at android.view.View.layout(View.java:17520)
    at android.view.ViewGroup.layout(ViewGroup.java:5612)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:17520)
    at android.view.ViewGroup.layout(ViewGroup.java:5612)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
    at android.view.View.layout(View.java:17520)
    at android.view.ViewGroup.layout(ViewGroup.java:5612)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:345)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
    at com.android.tools.idea.rendering.RenderTask.lambda$inflate$53(RenderTask.java:659)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by rcketscientist** [comment]
This implies that `handle` is null in `FastScoller.initHandleMovement` for designer purposes.

**Comment by micHar** [comment]
What is designer? Do you mean the Xamarin stuff? If so, I will not be able to fix it anytime soon. Maybe you can propose a PR. It's probably something easy, but I don't have the Xamarin environment set up.

**Comment by rcketscientist** [comment]
No, just generic Android Studio designer.  I haven't designed a widget in a while, but I think there's a flag that you can wrap code within to not process portions of code that would be undefined during development.  I'll take a look in the next couple days.
